---
title: "Lung Cancer"
description: |
  For analysts who are familiar with routinely collected national NHS data and provides a data dictionary, data quality and summary of methods for defining cohorts, characteristics and outcomes of lung cancer patients.
output: 
  distill::distill_article:
    #css: ["css/styles.css","css/accordion.css"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
:::{ .boxy .boxy-myinfo }

:::

# Stage 3 lung cancer

## NSCLC TNM8 Staging

```{r, echo=FALSE}
  df=read.csv("data/lung_NSCLC_TNM8_staging.csv",row.names=1,header=T,sep="\t")
  df[3:4,1] = kableExtra::cell_spec(df[3:4,1], color="black", background="#a9d18e")
  df[1:3,2] = kableExtra::cell_spec(df[1:3,2], color="black", background="#a9d18e")
  df[1:5,3] = kableExtra::cell_spec(df[1:5,3], color="red", background="#ffff00")
  df[1:5,4] = kableExtra::cell_spec(df[1:5,4], color="red", background="#ffff00")
  df[4,2]   = kableExtra::cell_spec(df[4,2],   color="red", background="#ffff00")
  df[5,1:2] = kableExtra::cell_spec(df[5,1:2], color="red", background="#ffff00")
  knitr::kable(df, booktabs=TRUE, escape=FALSE)
```

## Biomarker Time Points

```{r, echo=FALSE}
 df=read.csv("data/lung_biomarker_time_points.csv",header=T,sep="\t")
 df %>%
   kable(booktabs=TRUE) %>%
   kable_styling() %>%
   row_spec(row=c(1,9),        color="black", background="#a9d18e") %>%
   row_spec(row=c(2:8,10:13),   color="black", background="#ffe699")
 ```